---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cluster-ytsaurus-tech-v1-ytsaurus
  failurePolicy: Fail
  name: mytsaurus.kb.io
  rules:
  - apiGroups:
    - cluster.ytsaurus.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ytsaurus
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cluster-ytsaurus-tech-v1-ytsaurus
  failurePolicy: Fail
  name: vytsaurus.kb.io
  rules:
  - apiGroups:
    - cluster.ytsaurus.tech
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ytsaurus
  sideEffects: None
