---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - spyts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - spyts/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - spyts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - ytsaurus
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - ytsaurus/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.ytsaurus.tech
  resources:
  - ytsaurus/status
  verbs:
  - get
  - patch
  - update
