apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
  labels:
    name: jupyterlab
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    name: jupyterlab

---
apiVersion: v1
kind: Service
metadata:
  name: jupyterlab-headless
  labels:
    name: jupyterlab
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    name: jupyterlab

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jupyterlab
  labels:
    name: jupyterlab
spec:
  replicas: 1
  serviceName: jupyter-headless
  selector:
    matchLabels:
      name: jupyterlab
  template:
    metadata:
      labels:
        name: jupyterlab
    spec:
      containers:
        - name: jupyterlab
          image: ytsaurus/jupyter-tutorial:0.0.23
          env:
            - name: JUPYTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ytadminsec
                  key: token
            - name: YT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ytadminsec
                  key: token
            - name: YT_PROXY
              value: http-proxies-lb.default.svc.cluster.local
            - name: CHYT_CTL_ADDRESS
              value: chyt.default.svc.cluster.local
            - name: YT_UI_URL
              value: https://my-ip:port/ytdemo
          command:
            - /bin/bash
            - -c
            - |
              start.sh jupyter lab --ip='0.0.0.0' --port 8888 --notebook-dir=/home/jovyan/tutorial
          resources:
            requests:
              cpu: 250m
              memory: 2G
      restartPolicy: Always
      setHostnameAsFQDN: true