apiVersion: cluster.ytsaurus.tech/v1
kind: Ytsaurus
metadata:
  name: ytdemo
spec:
  coreImage: ytsaurus/ytsaurus:unstable-0.0.2
  uiImage: ytsaurus/ui:stable

  adminCredentials:
    name: ytadminsec

  cellTag: 1

  discovery:
    instanceGroup:
      instanceCount: 1

  chyt:
    resources:
      limits:
        memory: 100Mi

  spyt:
    sparkVersion: '1.69.0'
    spytVersion: '1.69.3'

  masters:
    instanceGroup:
      instanceCount: 3
      volumeMounts:
        - name: master-data
          mountPath: /yt/master-data
      locations:
        - locationType: MasterChangelogs
          path: /yt/master-data/master-changelogs
        - locationType: MasterSnapshots
          path: /yt/master-data/master-snapshots

      volumeClaimTemplates:
        - metadata:
            name: master-data
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 20Gi

  httpProxies:
    serviceType: NodePort
    instanceGroup:
      instanceCount: 3

  rpcProxies:
    serviceType: LoadBalancer
    instanceGroup:
      instanceCount: 3

  dataNodes:
    instanceGroup:
      instanceCount: 3

      volumeMounts:
        - name: node-data
          mountPath: /yt/node-data

      locations:
        - locationType: ChunkStore
          path: /yt/node-data/chunk-store

      volumeClaimTemplates:
        - metadata:
            name: node-data
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 50Gi

  execNodes:
    instanceGroup:
      instanceCount: 3

      resources:
        limits:
          cpu: 3
          memory: 5Gi

      volumeMounts:
        - name: node-data
          mountPath: /yt/node-data

      volumes:
        - name: node-data
          emptyDir:
            sizeLimit: 40Gi

      locations:
        - locationType: ChunkCache
          path: /yt/node-data/chunk-cache
        - locationType: Slots
          path: /yt/node-data/slots

  tabletNodes:
    instanceGroup:
      instanceCount: 3

  queryTrackers:
    instanceGroup:
      instanceCount: 1

  yqlAgents:
    instanceGroup:
      instanceCount: 1

  schedulers:
    instanceGroup:
      instanceCount: 1

  controllerAgents:
    instanceGroup:
      instanceCount: 1

  ui:
    serviceType: NodePort
    instanceCount: 1
