apiVersion: cluster.ytsaurus.tech/v1
kind: Ytsaurus
metadata:
  name: minisaurus
spec:
  coreImage: ytsaurus/ytsaurus:stable-23.1.0-relwithdebinfo
  uiImage: ytsaurus/ui:stable

  useIpv6: false

  configOverrides:
    name: minisaurus-overrides

  adminCredentials:
    name: ytadminsec

  discovery:
    instanceCount: 1

    # Make reusable loggers config with yaml anchor.
    loggers: &loggers
      - name: debug
        compression: zstd
        minLogLevel: debug
        writerType: file
        rotationPolicy: &rotationPolicy
          maxTotalSizeToKeep: 10000000
          rotationPeriodMilliseconds: 900000
        categoriesFilter:
          type: exclude
          values: ["Bus"]
      - name: info
        minLogLevel: info
        writerType: file
        rotationPolicy: *rotationPolicy
      - name: error
        minLogLevel: error
        writerType: stderr

  primaryMasters:
    instanceCount: 1
    cellTag: 1
    loggers: *loggers
    locations:
      - locationType: MasterChangelogs
        path: /yt/master-data/master-changelogs
      - locationType: MasterSnapshots
        path: /yt/master-data/master-snapshots

    volumeMounts:
      - name: master-data
        mountPath: /yt/master-data

    volumeClaimTemplates:
      - metadata:
          name: master-data
        spec:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 5Gi

  httpProxies:
    - serviceType: NodePort
      loggers: *loggers
      instanceCount: 1
      role: default
      transport:
        httpsSecret:
          name: minisaurus-https-secret
    - serviceType: NodePort
      loggers: *loggers
      instanceCount: 1
      role: control
      transport:
        httpsSecret:
          name: minisaurus-https-control-secret
        disableHttp: true

  rpcProxies:
    - instanceCount: 1
      loggers: *loggers
      role: default
      transport:
        tlsSecret:
          name: minisaurus-rpc-secret
        tlsRequired: true
    - instanceCount: 1
      loggers: *loggers
      role: heavy
      transport:
        tlsSecret:
          name: minisaurus-rpc-heavy-secret

  dataNodes:
    - instanceCount: 1
      loggers: *loggers

      volumeMounts:
        - name: node-data
          mountPath: /yt/node-data

      locations:
        - locationType: ChunkStore
          path: /yt/node-data/chunk-store

      volumeClaimTemplates:
        - metadata:
            name: node-data
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 5Gi

  execNodes:
    - instanceCount: 1
      loggers: *loggers
      resources:
        limits:
          cpu: 1
          memory: 2Gi

      volumeMounts:
        - name: node-data
          mountPath: /yt/node-data

      volumes:
        - name: node-data
          emptyDir:
            sizeLimit: 5Gi

      locations:
        - locationType: ChunkCache
          path: /yt/node-data/chunk-cache
        - locationType: Slots
          path: /yt/node-data/slots

  schedulers:
    instanceCount: 1
    loggers: *loggers

  controllerAgents:
    instanceCount: 1
    loggers: *loggers

  ui:
    serviceType: NodePort
    instanceCount: 1

---
apiVersion: v1
kind: Secret
metadata:
  name: ytadminsec
type: Opaque
data:
  login: YWRtaW4=         # admin
  password: cGFzc3dvcmQ=  # password
  token: cGFzc3dvcmQ=     # password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minisaurus-overrides
data:

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: minisaurus-selfsigned-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minisaurus-ca
spec:
  isCA: true
  commonName: minisaurus-ca
  subject:
    organizations:
      - Minisaurus CA
  secretName: minisaurus-ca-secret
  issuerRef:
    kind: Issuer
    name: minisaurus-selfsigned-issuer

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: minisaurus-ca-issuer
spec:
  ca:
    secretName: minisaurus-ca-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minisaurus-https-cert
spec:
  dnsNames:
  - "*.minisaurus.svc"
  - "*.minisaurus.svc.cluster.local"
  - "*.http-proxies.minisaurus.svc"
  - "*.http-proxies.minisaurus.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: minisaurus-ca-issuer
  secretName: minisaurus-https-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minisaurus-https-control-cert
spec:
  dnsNames:
  - "*.minisaurus.svc"
  - "*.minisaurus.svc.cluster.local"
  - "*.http-proxies-control.minisaurus.svc"
  - "*.http-proxies-control.minisaurus.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: minisaurus-ca-issuer
  secretName: minisaurus-https-control-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minisaurus-rpc-cert
spec:
  dnsNames:
  - "*.rpc-proxies.minisaurus.svc"
  - "*.rpc-proxies.minisaurus.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: minisaurus-ca-issuer
  secretName: minisaurus-rpc-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minisaurus-rpc-heavy-cert
spec:
  dnsNames:
  - "*.rpc-proxies-heavy.minisaurus.svc"
  - "*.rpc-proxies-heavy.minisaurus.svc.cluster.local"
  issuerRef:
    kind: Issuer
    name: minisaurus-ca-issuer
  secretName: minisaurus-rpc-heavy-secret
