apiVersion: cluster.ytsaurus.tech/v1
kind: Ytsaurus
metadata:
  name: ytdemo
spec:
  coreImage: ytsaurus/ytsaurus:latest
  uiImage: ytsaurus/ui:stable

  adminCredentials:
    name: ytadminsec

  discovery:
    instanceCount: 1

  chyt:
    resources:
      limits:
        memory: 100Mi

  spyt:
    sparkVersion: '1.67.0'
    spytVersion: '1.67.3'

  primaryMasters:
    instanceCount: 3
    cellTag: 1
    locations:
      - locationType: MasterChangelogs
        path: /yt/master-data/master-changelogs
      - locationType: MasterSnapshots
        path: /yt/master-data/master-snapshots

    volumes:
      - name: master-data
        emptyDir:
          sizeLimit: 20Gi

    volumeMounts:
      - name: master-data
        mountPath: /yt/master-data

  httpProxies:
    - serviceType: NodePort
      instanceCount: 1

  rpcProxies:
    - instanceCount: 1

  dataNodes:
    - instanceCount: 3

      volumeMounts:
        - name: node-data
          mountPath: /yt/node-data

      volumes:
        - name: node-data
          emptyDir:
            sizeLimit: 50Gi

      locations:
        - locationType: ChunkStore
          path: /yt/node-data/chunk-store

  execNodes:
    - instanceCount: 4

      resources:
        limits:
          cpu: 5
          memory: 20Gi

      volumeMounts:
        - name: node-data
          mountPath: /yt/node-data

      volumes:
        - name: node-data
          emptyDir:
            sizeLimit: 40Gi

      locations:
        - locationType: ChunkCache
          path: /yt/node-data/chunk-cache
        - locationType: Slots
          path: /yt/node-data/slots

  tabletNodes:
    - instanceCount: 1

  queryTrackers:
    - instanceCount: 1

  schedulers:
    instanceCount: 1

  controllerAgents:
    instanceCount: 1

  ui:
    serviceType: NodePort
    instanceCount: 1
