name: Create issue

on:
  issues:
    types: [opened]

jobs:
  send:
    name:
    runs-on: trampoline
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_NOTIFICATIONS_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            New issue in *${{github.repository}}*: `${{github.event.issue.title}}`
            ${{github.server_url}}/${{github.repository}}/issues/${{github.event.issue.number}}

      - name: Create issue
        run: |
          ./scripts/sync_issue.py --create-issue --repo 'ytsaurus/yt-k8s-operator' --github-issue-id ${{github.event.issue.number}} --github-issue-title '${{github.event.issue.title}}' --github-issue-description '${{github.event.issue.body}}' --token ${{secrets.ROBOT_SUP_TOKEN}}

